<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		
	</PropertyGroup>
	<ItemGroup>
	  <AdditionalFiles Remove="Assets\Texture\Items\Weapons\Misc\**" />
	  <Compile Remove="Assets\Texture\Items\Weapons\Misc\**" />
	  <EmbeddedResource Remove="Assets\Texture\Items\Weapons\Misc\**" />
	  <None Remove="Assets\Texture\Items\Weapons\Misc\**" />
	</ItemGroup>

	<!-- References -->
	<ItemGroup>
	  <Folder Include="Assets\Texture\Items\Accessories\" />
	  <Folder Include="Assets\Texture\Items\Materials\" />
	  <Folder Include="Assets\Texture\Items\Tools\" />
	  <Folder Include="Assets\Texture\Items\Vanity\" />
	  <Folder Include="Content\Buffs\" />
	  <Folder Include="Globals\Graphics\ModDusts\" />
	  <Folder Include="Globals\Instances\Tiles\" />
	</ItemGroup>

</Project>